name: K8S Integration - Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag gmehta3/hello-world:${{ github.sha }}
        docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push gmehta3/hello-world:${{ github.sha }}
        docker logout
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        
    - uses: azure/setup-kubectl@v1
      with:
        version: '<version>' 
      id: install
    
    - uses: actions/checkout@v1
    - name: Download and run skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        ./skaffold deploy -i gmehta3/hello-world:${{ github.sha }}


        
